In [ ]:
f= open("c:/테스트폴더/새파일.txt","r")
lines = f.readlines()
f.close()
print(lines)
list1 =[]
for item in lines:
    list1.append(item.replace("\n",""))
print(list1)

In [ ]:
f= open("c:/테스트폴더/새파일.txt","r")
page=f.read()
f.close()
print(page)
refined_list = page.split("\n")
print(refined_list)

In [ ]:
f= open("c:/테스트폴더/새파일.txt","a")
f.write("abcdefghi")
f.close()

In [ ]:
# 문자 추가하기(위와 같은 것)
with open("c:/테스트폴더/새파일.txt","a")as f:
    f.write("ㅋㅋㅋ")
f.close()

In [ ]:
# 절차지향적프로그래밍 procedure, 객체지향적 프로그래밍 class, object

In [ ]:
class FourCal:
    # self.first라는 구성성분이 있는 것이다
    # self.secon라는 구성성분이 class 안에 있다.
    def setdata(self, a,b):
        self.first=a
        self.second=b
    def add(self):     # 동작, self가 들어가줘야함 약속
        result=self.first+self.second
        return result  # self 안붙음
    #self가 붙으면 class의 구성요소가 됨
    def mul(self): 
        result=self.first*self.second
        return result
aCal = FourCal()
bCal = FourCal()
aCal.setdata(4,2)
print(aCal.add())
bCal.setdata(3,8)
print(bCal.add())

In [ ]:
class FourCal:
    def __init__(self, a,b):
        self.first=a
        self.second=b
    def add(self):    
        result=self.first+self.second
        return result 
    def mul(self): 
        result=self.first*self.second
        return result
aCal = FourCal(4, 2)
bCal = FourCal(3, 8)
print(aCal.add())
print(bCal.add())

In [ ]:
# MoreFourCal 사용한 코드
class FourCal:
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second 
        return result
    def mul(self):
        result = self.first * self.second 
        return result
    def div(self):
        result = self.first / self.second 
        return result
class MoreFourCal(FourCal): #부모를 입력받아서 계승함(상속받음) / MoreFourCal은 사칙연산에 대한 고민 X (+기능인 pow까지 가능)
    def pow(self):
        result = self.first**self.second
        return result
    
c = MoreFourCal(4,2)
d = c.pow()
print(d)

In [ ]:
class FourCal:
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second 
        return result
    def mul(self):
        result = self.first * self.second 
        return result
    def div(self):
        result = self.first / self.second 
        return result
class MoreFourCal(FourCal): #부모를 입력받아서 계승함(상속받음) / MoreFourCal은 사칙연산에 대한 고민 X (+기능인 pow까지 가능)
    def pow(self):
        result = self.first**self.second
        return result
    def div(self):
        if self.second == 0:
            self.second = 0.00000000000001
        result = self.first/self.second
        return result
c = MoreFourCal(4,0)
d = c.pow()
print(d)

In [ ]:
# 클래스 변수 기본
class MyMath:
    MyPI = 3.14
    
mm = MyMath()
print(mm.MyPI)

In [1]:
class MyMath:
    MyPI = 3.14
    
mm1 = MyMath()
mm1.MyPI = 4
mm2 = MyMath()
print(mm1.MyPI, mm2.MyPI)

4 3.14


In [8]:
import mod1 
print(mod1.add_mod1(3,4))
print(mod1.sub_mod1(3,4))

7
-1


In [10]:
import mod1 
print(mod1.add_mod1(3,4))
print(mod1.sub_mod1(3,4))

7
-1


In [9]:
import mod2
print(mod2.add_mod2(3,4))
print(mod2.PI)
mm2 = mod2.Math_mod2()
print(mm2.solve(2))

7
3.14
12.56


In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
try:
    print(4/0)
except ZeroDivisionError as e:
    print(4/0.0000000000000001)
finally:
    

4e+16


In [18]:
def positive(l):
    result=[]
    for  i in l:
        if i>0:
            result.append(i)
    return result
print(positive([1,-3,2,0,-5,6]))

[1, 2, 6]


In [20]:
def positive(x):
    return x >0

data=[1,-3,2,0,-5,6]
f=filter(positive, data)
print(list(f))

[1, 2, 6]


In [21]:
data=[1,-3,2,0,-5,6]
list(filter(lambda x:x>0, data))

[1, 2, 6]

In [22]:
a = input("숫자를 입력하세요")
print(a)

숫자를 입력하세요10
10


In [25]:
a,b,c,d,e = map(int, input("숫자 5개를 입력하세요").split())
print(a+1, b+1, c+1,d+1, e+1)

숫자 5개를 입력하세요1 2 3 4 5
2 3 4 5 6


In [27]:
data1 = [1,2,3]
data2 = [4,5,6]
data3 = [7,8,9]
list(zip(data1,data2,data3))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [30]:
import os
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\CPB06GameN\\AppData\\Roaming',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'DESKTOP-DT4Q4RC',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
        'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\CPB06GameN',
        'JAVA_HOME': 'C:\\Program Files\\Java\\jdk-16.0.1',
        'LOCALAPPDATA': 'C:\\Users\\CPB06GameN\\AppData\\Local',
        'LOGONSERVER': '\\\\DESKTOP-DT4Q4RC',
        'NUMBER_OF_PROCESSORS': '12',
        'ONEDRIVE': 'C:\\Users\\CPB06GameN\\OneDrive',
        'OS': 'Windows_NT',
        'PATH': 'C:\\ProgramData\\Anaconda3

In [32]:
os.getcwd()

'C:\\Users\\CPB06GameN\\내주피터노트파일들'

In [35]:
import glob
glob.glob('C:\\Users\\CPB06GameN\\내주피터노트파일들\\*.py')

['C:\\Users\\CPB06GameN\\내주피터노트파일들\\mod1.py',
 'C:\\Users\\CPB06GameN\\내주피터노트파일들\\mod2.py']

In [36]:
data = [6,7.5,8,0,1]
arr=np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [37]:
data2d = [[1,2,3,4],[5,6,7,8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [38]:
arr2d = np.array(data2d)

In [39]:
arr2d.ndim   # array의 차원

2

In [40]:
arr2d.shape  # array의 형태

(2, 4)

In [41]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros((2,3,2))   #(층, 행 ,열)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [46]:
np.zeros((2,3,2)).dtype

dtype('float64')

In [47]:
arr1 = np.zeros((2,3))
arr2 = np.ones_like(arr1)
arr2.shape

(2, 3)

In [50]:
arr3 = np.full((2,3),5)
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [49]:
# 대각행렬
arr4 = np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])